const { ethers } = require("ethers");
const fs = require("fs");
const path = require("path");
require("dotenv").config();

async function main() {
    const provider = new ethers.JsonRpcProvider("https://sepolia-rollup.arbitrum.io/rpc");
    const wallet = new ethers.Wallet(process.env.PRIVATE_KEY, provider);

    console.log("Deploying from:", wallet.address);

    // Read ABI and Bytecode generated by solcjs
    // Filename format from solcjs is usually: contracts_PropShieldLending_sol_PropShieldLending.abi
    const abiName = "contracts_PropShieldLending_sol_PropShieldLending.abi";
    const binName = "contracts_PropShieldLending_sol_PropShieldLending.bin";

    const abiPath = path.join(__dirname, "../artifacts", abiName);
    const binPath = path.join(__dirname, "../artifacts", binName);

    if (!fs.existsSync(abiPath) || !fs.existsSync(binPath)) {
        throw new Error(`Artifacts not found at ${abiPath} or ${binPath}`);
    }

    const abi = fs.readFileSync(abiPath, "utf8");
    const bin = fs.readFileSync(binPath, "utf8");

    const factory = new ethers.ContractFactory(abi, bin, wallet);
    const contract = await factory.deploy();

    console.log("Deploy tx sent:", contract.deploymentTransaction().hash);

    await contract.waitForDeployment();
    const address = await contract.getAddress();

    console.log("PropShieldLending deployed to:", address);

    return address;
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
